/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.PermintaanPenjemputan;

import view.VerifikasiPenjemputan.VerifPenjemputan;

/**
 *
 * @author HUMAIRA
 */
public class PeralatanSuhu extends javax.swing.JFrame {

    /**
     * Creates new form PeralatanSuhu
     */
    public PeralatanSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Kategori = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        Kategori1 = new javax.swing.JButton();
        PermintaanP = new javax.swing.JLabel();
        Permintaan = new javax.swing.JPanel();
        Alamat = new javax.swing.JLabel();
        Pemesan = new javax.swing.JLabel();
        Barang = new javax.swing.JLabel();
        Jarak = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        Terima = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();

        Header.setBackground(new java.awt.Color(202, 229, 255));

        Kategori.setBackground(new java.awt.Color(202, 229, 255));
        Kategori.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Kategori.setText("< Lampu");
        Kategori.setAlignmentY(0.0F);
        Kategori.setBorderPainted(false);
        Kategori.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Kategori)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Kategori)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 640));

        Header1.setBackground(new java.awt.Color(202, 229, 255));

        Kategori1.setBackground(new java.awt.Color(202, 229, 255));
        Kategori1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Kategori1.setText("< Peralatan Pertukaran Suhu");
        Kategori1.setAlignmentY(0.0F);
        Kategori1.setBorderPainted(false);
        Kategori1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Kategori1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kategori1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Header1Layout = new javax.swing.GroupLayout(Header1);
        Header1.setLayout(Header1Layout);
        Header1Layout.setHorizontalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Kategori1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Header1Layout.setVerticalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Kategori1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PermintaanP.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        PermintaanP.setText("Permintaan Penjemputan");

        Permintaan.setBackground(new java.awt.Color(217, 217, 217));
        Permintaan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Alamat.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        Alamat.setText("Jl. Dr. Setiabudi No.193, Gegerkalong, Kec. Sukasari, Kota Bandung");

        Pemesan.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        Pemesan.setText("Pemesan : Davina kusuma");

        Barang.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        Barang.setText("Barang : Lampu");

        Jarak.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        Jarak.setText("700 m");

        Waktu.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        Waktu.setText("3 menit");

        Terima.setBackground(new java.awt.Color(202, 229, 255));
        Terima.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        Terima.setText("Terima");
        Terima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PermintaanLayout = new javax.swing.GroupLayout(Permintaan);
        Permintaan.setLayout(PermintaanLayout);
        PermintaanLayout.setHorizontalGroup(
            PermintaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PermintaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PermintaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PermintaanLayout.createSequentialGroup()
                        .addComponent(Alamat)
                        .addGap(0, 453, Short.MAX_VALUE))
                    .addGroup(PermintaanLayout.createSequentialGroup()
                        .addComponent(Pemesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jarak))
                    .addGroup(PermintaanLayout.createSequentialGroup()
                        .addComponent(Barang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Waktu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PermintaanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Terima)))
                .addContainerGap())
        );
        PermintaanLayout.setVerticalGroup(
            PermintaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PermintaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PermintaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pemesan)
                    .addComponent(Jarak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PermintaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Barang)
                    .addComponent(Waktu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Terima)
                .addContainerGap())
        );

        Menu.setBackground(new java.awt.Color(202, 229, 255));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PermintaanP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Permintaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PermintaanP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Permintaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriActionPerformed

    private void Kategori1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kategori1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kategori1ActionPerformed

    private void TerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerimaActionPerformed
        // TODO add your handling code here:
        new VerifPenjemputan().setVisible(true);

    }//GEN-LAST:event_TerimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeralatanSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeralatanSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeralatanSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeralatanSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeralatanSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Barang;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header1;
    private javax.swing.JLabel Jarak;
    private javax.swing.JButton Kategori;
    private javax.swing.JButton Kategori1;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Pemesan;
    private javax.swing.JPanel Permintaan;
    private javax.swing.JLabel PermintaanP;
    private javax.swing.JButton Terima;
    private javax.swing.JLabel Waktu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
